# Generated by Django 6.0 on 2025-12-17 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_loyaltyredemption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='loyalty_points',
        ),
        migrations.DeleteModel(
            name='LoyaltyRedemption',
        ),
    ]
