# Generated by Django 6.0 on 2026-08-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0004_add_stripe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('cash_on_delivery', 'Cash on delivery')], default='card', max_length=20),
        ),
    ]
